name: CI
on:
  pull_request:
    branches:
      - main
      - beta
  push:
    branches:
      - main
      - beta

jobs:
  setup_and_checks:
    name: Setup dependencies and checks
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]
    steps:
      - name: Common Steps
        id: common
        run: |
          echo "common_step=yes" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Use cache dependencies
        if: env.common_step == 'yes'
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            **/node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-modules-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/yarn.lock') }}s
      - name: Install packages
        run: yarn install --frozen-lockfile
      - name: ESLint
        run: yarn lint:ci
        continue-on-error: true
      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@1.2.0
        if: always()
        continue-on-error: true
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          report-json: 'eslint_report.json'
      - name: Prettier
        run: yarn format:check

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]
    needs: setup_and_checks
    steps:
      - name: Common Steps
        id: common
        run: |
          echo "common_step=yes" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Use cache dependencies
        if: env.common_step == 'yes'
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            **/node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-modules-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/yarn.lock') }}s
      - name: Install packages
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build

  cypress_tests:
    name: Cypress E2E Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox, edge]
        node: [16]
    needs: build
    steps:
      - name: Common Steps
        id: common
        run: |
          echo "common_step=yes" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Use cache dependencies
        if: env.common_step == 'yes'
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            **/node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-modules-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/yarn.lock') }}s
      - name: Install packages
        run: yarn install --frozen-lockfile
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v2
        with:
          start: yarn dev
          wait-on: 'http://localhost:3000'
          cache-key: ${{ runner.os }}-modules-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/yarn.lock') }}s
          config-file: cypress.config.ts
          browser: ${{ matrix.browser }}
